[project]
name = "info698-capstone"
version = "0.1.0"
description = "Agent Based RAG system over PMC"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chromadb>=0.6.3",
    "datasets>=3.4.1",
    "huggingface-hub>=0.29.3",
    "ipywidgets>=8.1.5",
    "langchain>=0.3.20",
    "langchain-community>=0.3.19",
    "langchain-core>=0.3.45",
    "langchain-openai>=0.3.8",
    "langchain-weaviate>=0.0.4",
    "langgraph>=0.3.21",
    "langgraph-prebuilt>=0.1.7",
    "langsmith>=0.3.15",
    "openai>=1.66.3",
    "pandas>=2.2.3",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "sentence-transformers>=3.4.1",
    "streamlit>=1.42.2",
    "supabase>=2.14.0",
    "tiktoken>=0.9.0",
    "watchdog>=6.0.0",
    "weaviate-client>=4.11.3",
    "wikipedia>=1.4.0",
]
